# Generated by Django 6.0 on 2025-12-24 11:48

from django.db import migrations, models
from django.template.defaultfilters import slugify
from unidecode import unidecode


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
def gen_slugs(apps, schema_editor):
    City = apps.get_model('city', 'City')
    for city in City.objects.all():
        print(f"Обробка міста: {city.name}") # ТИ МАЄШ ПОБАЧИТИ ЦЕ В КОНСОЛІ
        city.slug = slugify(unidecode(city.name))
        city.save()