# Generated by Django 6.0 on 2025-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_slug_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True, verbose_name='URL-адреса'),
            preserve_default=False,
        ),
    ]
