# Generated by Django 6.0 on 2025-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_carrier',
            field=models.BooleanField(default=False, verbose_name='Перевізник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=False, verbose_name='Пасажир'),
        ),
    ]
