# Generated by Django 6.0 on 2025-12-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_carrier_alter_user_is_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Будь-яка комбінація символів', max_length=255, unique=True),
        ),
    ]
