# Generated by Django 6.0 on 2025-12-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_carrierprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='phone',
        ),
    ]
