# Generated by Django 6.0 on 2025-12-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_carrierprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
