# Generated by Django 6.0 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passengerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierprofile',
            name='phone',
            field=models.CharField(default=123, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
