# Generated by Django 6.0 on 2025-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_point',
            field=models.CharField(default=1, max_length=100, verbose_name='Місце висадки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_point',
            field=models.CharField(default=1, max_length=100, verbose_name='Місце посадки'),
            preserve_default=False,
        ),
    ]
