# Generated by Django 6.0 on 2025-12-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_arrival_point_booking_departure_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_phone',
        ),
    ]
