# Generated by Django 6.0 on 2025-12-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_total_price'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Відстань (км)')),
                ('duration_hr', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тривалість (год)')),
                ('cached_at', models.DateTimeField(auto_now_add=True, verbose_name='Закешовано')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_end_routes', to='city.city', verbose_name='Кінцеве місто')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_start_routes', to='city.city', verbose_name='Початкове місто')),
            ],
            options={
                'verbose_name': 'Кеш відстаней маршрутів',
                'verbose_name_plural': 'Кеші відстаней маршрутів',
                'indexes': [models.Index(fields=['start_city', 'end_city'], name='booking_rou_start_c_5ce9f7_idx')],
                'unique_together': {('start_city', 'end_city')},
            },
        ),
    ]
