# Generated by Django 6.0 on 2025-12-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_routedistancecache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routedistancecache',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='routedistancecache',
            name='booking_rou_start_c_5ce9f7_idx',
        ),
        migrations.DeleteModel(
            name='RouteDistanceCache',
        ),
    ]
