# Generated by Django 6.0 on 2025-12-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-boosted_at', '-id'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршрути'},
        ),
        migrations.AddField(
            model_name='route',
            name='boosted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата підняття в топ'),
        ),
    ]
