# Generated by Django 6.0 on 2025-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_route_options_route_boosted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-top_until', '-id'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршрути'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='boosted_at',
        ),
        migrations.AddField(
            model_name='route',
            name='top_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ТОП діє до'),
        ),
    ]
