# Generated by Django 6.0 on 2025-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_route_options_remove_route_boosted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='top_until',
            field=models.DateField(blank=True, null=True, verbose_name='ТОП діє до'),
        ),
    ]
