# Generated by Django 6.0 on 2025-12-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_route_top_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='top_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ТОП діє до'),
        ),
    ]
