# Generated by Django 6.0 on 2025-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_route_top_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_parcel',
            field=models.BooleanField(default=True, help_text='Чи приймає цей маршрут посилки для передачі', verbose_name='Доставка посилок'),
        ),
        migrations.AddField(
            model_name='route',
            name='is_passenger',
            field=models.BooleanField(default=True, help_text='Чи доступне бронювання місць для пасажирів', verbose_name='Пасажирські перевезення'),
        ),
        migrations.AddField(
            model_name='route',
            name='min_parcel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мінімальна ціна посилки'),
        ),
        migrations.AddField(
            model_name='route',
            name='min_trip_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мінімальна ціна поїздки'),
        ),
        migrations.AddField(
            model_name='route',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна за 1 кг'),
        ),
        migrations.AddField(
            model_name='route',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна за 1 км'),
        ),
    ]
