# Generated by Django 6.0 on 2025-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_route_is_parcel_route_is_passenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Порядок'),
        ),
    ]
