# Generated by Django 6.0 on 2025-12-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('trips', '0007_alter_routestop_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_distances', to='city.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_distances', to='city.city')),
            ],
            options={
                'verbose_name': 'Кеш відстані',
                'verbose_name_plural': 'Кеш відстаней',
                'unique_together': {('city_from', 'city_to')},
            },
        ),
    ]
